services:
  app:
    container_name: "ytdl-web-dev"
    build:
      context: .
      target: dev
    ports:
      - 8080:8080
    develop:
      watch:
        - action: sync
          path: .
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
    environment:
      - VITE_API_URL=http://127.0.0.1:8000/api
    networks:
      - default
  app-prod:
    container_name: "ytdl-web-prod"
    build:
      context: .
      target: prod
      args:
        - API_URL=http://127.0.0.1:8000/api
    ports:
      - 8081:8080
    networks:
      - default