version: '3.7'
services:
  ytdl-web:
    container_name: "ytdl-web"
    build:
      context: .
      target: dev
    ports:
      - 8080:80
    volumes:
      - "./src/:/app/src"
    environment:
      - VITE_API_URL=http://127.0.0.1:8000/api
    networks:
      - default
  ytdl-web-prod:
    container_name: "ytdl-web-prod"
    build:
      context: .
      target: prod
      args:
        - API_URL=http://127.0.0.1:8000/api
    ports:
      - 8081:8080
    networks:
      - default