version: '3.7'
services:
  ytdl-web:
    container_name: "ytdl-web"
    build:
      context: ./web/
      target: dev
    ports:
      - 8080:8080
    volumes:
      - "./web/:/app"
    environment:
      - API_URL=http://127.0.0.1:8000/api
    depends_on:
      - ytdl-api
    networks:
      - default

networks:
  default:
    name: "ytdl-network"
