version: '3.7'
services:
  ytdl-web:
    container_name: "ytdl-web"
    build:
      context: .
      target: dev
    ports:
      - 8080:8080
    volumes:
      - ".:/app"
    environment:
      - API_URL=http://127.0.0.1:8000/api
    networks:
      - default
